import { SIM_HZ } from '../types';
import type { EntityKind } from '../types';
import type { EntityBlueprint } from './schema';

export const BASE_ENTITY_BLUEPRINTS: Record<EntityKind, EntityBlueprint> = {
  worker: {
    kind: 'worker',
    class: 'unit',
    hp: 30,
    damage: 3,
    armor: 0,
    range: 1,
    speed: 4,
    sight: 4,
    cost: { gold: 55 },
    buildTicks: SIM_HZ * 9,
    attackTicks: SIM_HZ,
    tileW: 1,
    tileH: 1,
    tags: ['worker', 'human', 'economy'],
    roleText: 'eco / build',
  },
  footman: {
    kind: 'footman',
    class: 'unit',
    hp: 72,
    damage: 8,
    armor: 4,
    range: 1,
    speed: 4,
    sight: 5,
    cost: { gold: 85 },
    buildTicks: SIM_HZ * 14,
    attackTicks: SIM_HZ,
    tileW: 1,
    tileH: 1,
    tags: ['frontline', 'human', 'hold'],
    roleText: 'frontline core',
  },
  archer: {
    kind: 'archer',
    class: 'unit',
    hp: 34,
    damage: 8,
    armor: 0,
    range: 6,
    speed: 4,
    sight: 7,
    cost: { gold: 95 },
    buildTicks: SIM_HZ * 17,
    attackTicks: Math.round(SIM_HZ * 1.4),
    tileW: 1,
    tileH: 1,
    tags: ['backline', 'human', 'support'],
    roleText: 'backline support',
  },
  knight: {
    kind: 'knight',
    class: 'unit',
    hp: 125,
    damage: 14,
    armor: 6,
    range: 1,
    speed: 4,
    sight: 5,
    cost: { gold: 165 },
    buildTicks: SIM_HZ * 21,
    attackTicks: Math.round(SIM_HZ * 1.5),
    tileW: 1,
    tileH: 1,
    tags: ['frontline', 'human', 'elite'],
    roleText: 'elite anchor',
  },
  peon: {
    kind: 'peon',
    class: 'unit',
    hp: 30,
    damage: 3,
    armor: 0,
    range: 1,
    speed: 4,
    sight: 4,
    cost: { gold: 55 },
    buildTicks: SIM_HZ * 9,
    attackTicks: SIM_HZ,
    tileW: 1,
    tileH: 1,
    tags: ['worker', 'orc', 'economy'],
    roleText: 'eco / build',
  },
  grunt: {
    kind: 'grunt',
    class: 'unit',
    hp: 92,
    damage: 10,
    armor: 4,
    range: 1,
    speed: 3,
    sight: 5,
    cost: { gold: 105 },
    buildTicks: SIM_HZ * 17,
    attackTicks: Math.round(SIM_HZ * 1.2),
    tileW: 1,
    tileH: 1,
    tags: ['frontline', 'orc', 'shock'],
    roleText: 'shock frontline',
  },
  troll: {
    kind: 'troll',
    class: 'unit',
    hp: 36,
    damage: 10,
    armor: 0,
    range: 4,
    speed: 4,
    sight: 7,
    cost: { gold: 95 },
    buildTicks: SIM_HZ * 17,
    attackTicks: Math.round(SIM_HZ * 1.4),
    tileW: 1,
    tileH: 1,
    tags: ['backline', 'orc', 'pressure'],
    roleText: 'ranged pressure',
  },
  ogreFighter: {
    kind: 'ogreFighter',
    class: 'unit',
    hp: 150,
    damage: 16,
    armor: 4,
    range: 1,
    speed: 3,
    sight: 5,
    cost: { gold: 180 },
    buildTicks: SIM_HZ * 23,
    attackTicks: Math.round(SIM_HZ * 1.8),
    tileW: 1,
    tileH: 1,
    tags: ['frontline', 'orc', 'elite'],
    roleText: 'elite bruiser',
  },
  townhall: {
    kind: 'townhall',
    class: 'building',
    hp: 1200,
    damage: 0,
    armor: 5,
    range: 0,
    speed: 0,
    sight: 8,
    cost: { gold: 0 },
    buildTicks: 0,
    attackTicks: 0,
    tileW: 3,
    tileH: 3,
    supplyProvided: 4,
    tags: ['structure', 'base'],
    roleText: 'main base',
  },
  barracks: {
    kind: 'barracks',
    class: 'building',
    hp: 800,
    damage: 0,
    armor: 3,
    range: 0,
    speed: 0,
    sight: 4,
    cost: { gold: 360 },
    buildTicks: SIM_HZ * 34,
    attackTicks: 0,
    tileW: 3,
    tileH: 2,
    tags: ['structure', 'production'],
    roleText: 'production',
  },
  farm: {
    kind: 'farm',
    class: 'building',
    hp: 400,
    damage: 0,
    armor: 1,
    range: 0,
    speed: 0,
    sight: 4,
    cost: { gold: 180 },
    buildTicks: SIM_HZ * 18,
    attackTicks: 0,
    tileW: 2,
    tileH: 2,
    supplyProvided: 4,
    tags: ['structure', 'supply'],
    roleText: 'supply',
  },
  wall: {
    kind: 'wall',
    class: 'building',
    hp: 200,
    damage: 0,
    armor: 5,
    range: 0,
    speed: 0,
    sight: 6,
    cost: { gold: 50 },
    buildTicks: SIM_HZ * 5,
    attackTicks: 0,
    tileW: 1,
    tileH: 1,
    tags: ['structure', 'fortified'],
    roleText: 'fortified hold',
  },
  tower: {
    kind: 'tower',
    class: 'building',
    hp: 520,
    damage: 9,
    armor: 2,
    range: 6,
    speed: 0,
    sight: 8,
    cost: { gold: 275 },
    buildTicks: SIM_HZ * 28,
    attackTicks: Math.round(SIM_HZ * 1.0),
    tileW: 2,
    tileH: 2,
    tags: ['structure', 'defense'],
    roleText: 'defensive anchor',
  },
  barrier: {
    kind: 'barrier',
    class: 'building',
    hp: 260,
    damage: 0,
    armor: 0,
    range: 0,
    speed: 0,
    sight: 0,
    cost: { gold: 0 },
    buildTicks: 0,
    attackTicks: 0,
    tileW: 2,
    tileH: 1,
    tags: ['structure', 'neutral', 'blocker'],
    roleText: 'destructible blocker',
  },
  construction: {
    kind: 'construction',
    class: 'scaffold',
    hp: 1,
    damage: 0,
    armor: 0,
    range: 0,
    speed: 0,
    sight: 0,
    cost: { gold: 0 },
    buildTicks: 1,
    attackTicks: 0,
    tileW: 1,
    tileH: 1,
    tags: ['scaffold'],
  },
  goldmine: {
    kind: 'goldmine',
    class: 'resource',
    hp: 9999,
    damage: 0,
    armor: 0,
    range: 0,
    speed: 0,
    sight: 0,
    cost: { gold: 0 },
    buildTicks: 0,
    attackTicks: 0,
    tileW: 2,
    tileH: 2,
    tags: ['resource'],
    roleText: 'resource node',
  },
};
